blank_issues_enabled: false
contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #assemblybacterias channel"
    url: https://nfcore.slack.com/channels/assemblybacterias
    about: Discussion about the nf-core/assemblybacterias pipeline
